#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

/bin/echo "$0 starts..."
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys

# mount all other filesystems (/etc/fstab)
/bin/echo "Mounting other filesystems ..."
/bin/mount -a

rm -f /dev/rtc*
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

mkdir -p /dev/pts /dev/shm
/bin/mount -t devpts -o mode=620 none /dev/pts
/bin/mount -t tmpfs tmpfs /dev/shm
/bin/mount -t tmpfs tmpfs /tmp

if [ -f /etc/init.d/rc.extra ];then
	echo "rc.extra [bg]"
	/etc/init.d/rc.extra &
fi

if [ -f /etc/init.d/rc.sdcardboot ];then
	/etc/init.d/rc.sdcardboot
else
	/etc/init.d/rc.resizefs
fi

if [ -d /sys/class/remoteproc/remoteproc0 ];then
if [ -f /lib/firmware/cm4.img ];then
	echo "Boot cm4.img by remoteproc"
	echo cm4.img > /sys/class/remoteproc/remoteproc0/firmware
	echo start > /sys/class/remoteproc/remoteproc0/state
fi

if [ -f /lib/firmware/a926.img ];then
	echo "Boot a926.img by remoteproc"
	echo a926.img > /sys/class/remoteproc/remoteproc0/firmware
	echo start > /sys/class/remoteproc/remoteproc0/state
fi
fi

/bin/echo "End of $0"
