#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

/bin/echo "$0 starts..."
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys

# mount all other filesystems (/etc/fstab)
/bin/echo "Mounting other filesystems ..."
/bin/mount -a

rm -f /dev/rtc*
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

mkdir -p /dev/pts /dev/shm
/bin/mount -t devpts -o mode=620 none /dev/pts
/bin/mount -t tmpfs tmpfs /dev/shm
/bin/mount -t tmpfs tmpfs /tmp
/bin/mount -t devtmpfs -o mode=0755 none /dev

if [ -f /etc/init.d/rc.extra ];then
	echo "rc.extra [bg]"
	/etc/init.d/rc.extra &
fi

if [ -f /etc/init.d/rc.sdcardboot ];then
	/etc/init.d/rc.sdcardboot
else
	/etc/init.d/rc.resizefs
fi
/bin/echo "End of $0"

if [ -f /lib/firmware/rom ];then
	echo "boot nonos_B from openamp"
	echo rom > /sys/class/remoteproc/remoteproc0/firmware
	echo start >  /sys/class/remoteproc/remoteproc0/state
fi
