#!/bin/sh
#
# author: PoChou Chen
#

BASE_A=0xF8000000
BASE_B=0xF8800000

if [ $# -ne 4 ]; then
	echo "Usage: $0 [a|b] [group] [index] [value]"
	exit 1
fi

if [ "$1" != "a" ] && [ "$1" != "b" ]; then
	echo "Invalid chip. It should be be 'a' or 'b'."
	exit 1
fi

if [ "$1" = "a" ]; then
	BASE=$BASE_A
else
	BASE=$BASE_B
fi

group=$(($2))
index=$(($3))
value=$(($4))

devmem $(($BASE+$group*32*4+$index*4)) 32 $value

value=$(devmem $(($BASE+$group*32*4+$index*4)) 32)

printf "write register G%d.%d = 0x%08x (%d)\n" $group $index $value $value

